apiVersion: v1
data:
  pyfile: "import numpy as np\n\ndef handler(input: dict, context: object) -> dict:\n
    \   # Extrai as medições de uso de recursos\n    nb_cpus = 16\n    cpu_percentages
    = []\n    for i in range(1, nb_cpus + 1):\n        cpu_percentages.append(input.get(f'cpu_percent-{i}'))\n\n
    \   virtual_memory_total = input.get('virtual_memory-total')\n    virtual_memory_buffers
    = input.get('virtual_memory-buffers')\n    virtual_memory_cached = input.get('virtual_memory-cached')\n\n
    \   # Dados de tráfego de rede\n    bytes_sent = input.get('net_io_counters_eth0-bytes_sent1')\n
    \   bytes_recv = input.get('net_io_counters_eth0-bytes_recv1')\n\n    # Calcula
    a porcentagem de bytes de tráfego de saída\n    total_bytes = bytes_sent + bytes_recv\n
    \   percent_network_egress = (bytes_sent / total_bytes) * 100 if total_bytes >
    0 else 0\n\n    # Calcula a porcentagem de conteúdo em cache de memória\n    percent_memory_cache
    = ((virtual_memory_buffers + virtual_memory_cached) / virtual_memory_total) *
    100\n\n    # Calcula uma média móvel de utilização de cada CPU no ultimo minuto\n
    \   simple_moving_avgs = []\n    for i, cpu_percent_X in enumerate(cpu_percentages):\n
    \       X_utilizations = context['env'].get(f'cpu{i+1}_utilizations', [])\n        X_utilizations.append(cpu_percent_X)\n
    \       \n        if len(X_utilizations) > 60:\n            X_utilizations.pop(0)\n
    \       \n        context['env'][f'cpu{i+1}_utilizations'] = X_utilizations\n
    \       X_simple_moving_avg = np.mean(X_utilizations)\n        simple_moving_avgs.append(X_simple_moving_avg)\n
    \       \n    # Retorna a resposta\n    response  = dict()\n    response['percent-network-egress']
    = percent_network_egress\n    response['percent-memory-cache'] = percent_memory_cache\n\n
    \   for i, simple_moving_avg in enumerate(simple_moving_avgs):\n        response[f'moving-avg-cpu{i+1}']
    = simple_moving_avg\n\n    return response\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-08T15:50:19Z"
  name: pyfile
  namespace: victorribeiro
  resourceVersion: "3419719"
  uid: 5a7e01e4-223f-41a0-adda-3adef3dedf2d
