USERNAME=victor.henrique
REMOTE_MACHINE_IP=gorgona5
REMOTE_DASHBOARD_IP=localhost
DASHBOARD_PORT=8050
ssh -L localhost:$DASHBOARD_PORT:$REMOTE_DASHBOARD_IP:$DASHBOARD_PORT -N -f -l $USERNAME $REMOTE_MACHINE_IP